### ISSUE TITLE
终极锭无法合成，原因不明

### ISSUE THREAD

**Issue by albus12138** [TIMWTeam/This-Is-My-World-IV-Trial-of-God#26]
![image](https://user-images.githubusercontent.com/9742081/62462663-85e9c180-b7ba-11e9-9625-5591375b5618.png)

**Comment by YiChenCraft** [comment]
能合成，没问题，检查是不是因为摆错了或物品不对

**Comment by albus12138** [comment]
是Crafting Tweaker摆进去的，不知道问题出在哪
