### ISSUE TITLE
自然灵气祭坛- 中文状态-书籍不会显示模型投影

### ISSUE THREAD

**Issue by pbwind** [TIMWTeam/This-Is-My-World-IV-Trial-of-God#33]
偶然再youtube上看到有人玩这个模组，于是跟进。

简体中文的自然灵气书，再自然祭坛灌注 那一页，并没有自然祭坛的 摆放投影，只有后面铁锭的转换配方。

根据youtube视频、自己验证。

更改语言选项，英文、繁体中文。  在自然灌注祭坛那一页均有摆放投影。

**Comment by dong031001** [comment]
在最新一版的汉化资源包中已由我修正，可以等待汉化模组下一次自动更新后即可恢复正常

**Comment by pbwind** [comment]
> 在最新一版的汉化资源包中已由我修正，可以等待汉化模组下一次自动更新后即可恢复正常

请问再哪里可以手动下载。 谢谢

**Comment by YiChenCraft** [comment]
最新版已更新汉化资源包，未确认是否修复。

**Comment by YiChenCraft** [comment]
PS：汉化资源包所引发的未知内容，虽是因为我添加资源包引起，但也是我无法干涉和预知的。
因此可以考虑自行解决……当然也可以对问题进行汇报，我也会在下次更新时进行调整。
