### ISSUE TITLE
研究不给蓝图

### ISSUE THREAD

**Issue by Acc1143** [TIMWTeam/This-Is-My-World-IV-Trial-of-God#9]
第一个研究完成后没有给机械蓝图，点击完成后整个研究台变成5桶血之精华的那一个恶魔结晶研究
，再次点击开始研究没有反应。退出游戏重新进入发现进入第二个研究 让我提交能量和蓝图。但是此时并没有蓝图。
只在服务器中发现这个问题

**Comment by YiChenCraft** [comment]
因为模组原因，bug请提交模组作者
